Repository software-students-fall2021/project-setup-sneaky-seven, pull requests merged in 2021-12, with the labels that each got.

#147 disallow duplicate accounts from being added
  back-end/app.js
  back-end/functions/isDuplicateAccount.js
  back-end/functions/postAccessTokenToDatabase.js
  back-end/test/test.js
Labels: task

#151 improve design of project (spacing)
  front-end/src/components/RegistrationForm.js
  front-end/src/components/Statistics/Balance/index.js
  front-end/src/pages/Homepage.js
Labels: spike

#152 improve design of project (images)
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/src/components/Navbar/Navbar.js
  front-end/src/components/css/Navbar.css
  front-end/src/css/App.css
  front-end/src/css/background.png
Labels: spike

#154 Fix deploy tests
  back-end/test/test.js
Labels: spike

#164 fixed transaction amount color in transaction detail page
  front-end/src/pages/TransactionDetail.js
Labels: bug

#157 delete categories
  back-end/app.js
  back-end/functions/deleteCategory.js
  back-end/test/test.js
  front-end/src/api/index.js
  front-end/src/pages/Categories.js
  front-end/src/pages/EditCategory.js
  front-end/src/pages/css/IconGrid.css
Labels: task

#165 Remove accounts
  back-end/app.js
  back-end/functions/removeAccount.js
  back-end/test/test.js
  front-end/src/components/AccountDetail/AccountDetail.js
  front-end/src/components/Accounts/AccountsPage.js
Labels: task

#167 update readme and contributing
  CONTRIBUTING.md
  README.md
Labels: spike

#169 improve cat documentation
  back-end/constants/FAQData.js
  front-end/src/pages/Categories.js
Labels: task

#174 remove random intellij files
  .gitignore
  .idea/workspace.xml
  project-setup-sneaky-seven.iml
Labels: spike

#173 minor CSS fixes - fixed text wrapping with long words
  front-end/src/components/css/ContactForm.css
  front-end/src/components/css/Homepage.css
Labels: bug

#175 changes for deleting correct account
  back-end/app.js
  back-end/functions/removeAccount.js
  front-end/src/components/AccountDetail/AccountDetail.js
Labels: task
