Repository software-students-fall2021/project-setup-sneaky-seven, pull requests merged in 2021-11, with the labels that each got.

#51 Fix routing and api issues
  front-end/package-lock.json
  front-end/src/api/index.js
  front-end/src/api/mocks.js
  front-end/src/components/Accounts/AccountBackupData.js
  front-end/src/components/Navbar/NavbarWrapper.js
  front-end/src/components/Statistics/StatsNavbar/StatsNavbarWrapper.js
  front-end/src/pages/Accounts.js
  front-end/src/pages/Homepage.js
  front-end/src/pages/Statistics.js
  front-end/src/pages/TransactionDetail.js
  front-end/src/utils.js
Labels: spike

#61 filtered categories and added unit test
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  back-end/test/test.js
  front-end/src/components/Categories/CategoryList.js
Labels: task

#68 Display bank details in details page
  back-end/app.js
  front-end/src/components/AccountDetail/AccountDetail.js
  front-end/src/components/Accounts/AccountPanel.js
  front-end/src/components/Accounts/AccountsPage.js
  front-end/src/pages/Accounts.js
  tatusqq
Labels: task

#70 added contact form backend
  back-end/app.js
  front-end/src/components/ContactForm.js
  front-end/src/components/ContactFormConfirm.js
  front-end/src/components/Navbar/NavbarWrapper.js
  front-end/src/components/css/ContactForm.css
  front-end/src/pages/Contact.js
  front-end/src/pages/ContactConfirm.js
Labels: task

#72 update readme and contributing with new instructions
  CONTRIBUTING.md
  README.md
Labels: spike

#65 Add support for user-generated categories
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/test/test.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/api/index.js
  front-end/src/api/mocks.js
  front-end/src/components/Categories/CategoryData.js
  front-end/src/components/Categories/CategoryData.json
  front-end/src/components/Categories/CategoryList.js
  front-end/src/components/Categories/IconGrid.js
  front-end/src/components/Categories/IconList.js
  front-end/src/components/Categories/NewCategory.js
  front-end/src/components/Navbar/NavbarWrapper.js
  front-end/src/css/index.css
  front-end/src/pages/AddCategory.js
  front-end/src/pages/Categories.js
  front-end/src/pages/css/Categories.css
  front-end/src/pages/css/IconGrid.css
  front-end/src/utils.js
Labels: task

#73 added unit test for categories pages
  back-end/app.js
  back-end/test/test.js
Labels: spike

#77 added backend for faq and unit tests
  back-end/app.js
  back-end/test/test.js
  front-end/src/components/FAQ/FAQ.js
  front-end/src/components/FAQ/FAQData.js
Labels: task

#80 Add per-category transaction list
  back-end/app.js
  back-end/package.json
  front-end/src/api/index.js
  front-end/src/css/index.css
  front-end/src/pages/Categories.js
  front-end/src/pages/css/Categories.css
Labels: task

#81 set up tests for getting accounts
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/test/test.js
  front-end/package-lock.json
  package-lock.json
Labels: task

#82 connecting backend and stats page
  front-end/src/components/Statistics/Balance/BalanceByAccountList.js
  front-end/src/components/Statistics/Balance/index.js
  front-end/src/components/Statistics/Spending/index.js
  front-end/src/components/Statistics/StatsNavbar/StatsNavbarWrapper.js
  front-end/src/components/css/StatsNavbar.css
  front-end/src/pages/Homepage.js
  front-end/src/pages/Statistics.js
  front-end/src/pages/css/Statistics.css
Labels: task

#93 Refactor functions and constants to import into app.js
  back-end/app.js
  back-end/constants/FAQData.js
  back-end/constants/categories.js
  back-end/functions/constructAccountsArray.js
  back-end/functions/constructTransactionArray.js
  back-end/functions/formatError.js
  back-end/functions/postAccessTokenToDatabase.js
  back-end/functions/prettyPrintResponse.js
  back-end/schemas/accessTokenSchema.js
  back-end/test/test.js
Labels: spike

#99 Save access tokens to database under user account
  back-end/app.js
  back-end/functions/constructAccountsArray.js
  back-end/functions/constructTransactionArray.js
  back-end/functions/postAccessTokenToDatabase.js
  back-end/model/accessToken.js
  back-end/model/user.js
  back-end/schema/README.md
  back-end/schema/accessToken.js
  front-end/src/components/Accounts/AccountsPage.js
Labels: task

#105 added small unit test for constructTransactionArr
  CONTRIBUTING.md
  README.md
  back-end/app.js
  back-end/functions/constructTransactionArray.js
  back-end/package-lock.json
  back-end/test/test.js
Labels: spike

#106 Fetch user bank accounts across multiple banks from DB
  back-end/app.js
  back-end/functions/getAccessTokens.js
  front-end/src/components/Accounts/AccountsPage.js
Labels: task

#107 added infinite scroll for transactions page, fixed homepage transacti…
  back-end/app.js
  back-end/yarn 2.lock
  front-end/src/api/index.js
  front-end/src/components/HomePageTransactionList.js
  front-end/src/components/TransactionList.js
  front-end/src/pages/Homepage.js
  front-end/src/pages/Transactions.js
Labels: task, spike

#109 access token is fetched from db, refactored transactions, updated homepage
  back-end/app.js
  back-end/functions/constructTransactionArray.js
  back-end/functions/getAccessTokens.js
  back-end/functions/getTransactions.js
  back-end/functions/setTransactionCategoryInDatabase.js
  back-end/functions/setTransactionNotesInDatabase.js
  back-end/model/user.js
  back-end/schema/accessToken.js
  back-end/schema/transactions.js
  front-end/src/api/index.js
  front-end/src/api/mocks.js
  front-end/src/components/CategoryIcon.js
  front-end/src/components/HomePageTransactionList.js
  front-end/src/components/Navbar/NavbarWrapper.js
  front-end/src/components/TransactionList.js
  front-end/src/pages/TransactionDetail.js
Labels: task

#117 added tests and removed console.log statements
  back-end/app.js
  back-end/functions/constructTransactionArray.js
  back-end/test/test.js
Labels: spike

#119 added missing closing braces from before
  back-end/package-lock.json
  back-end/test/test.js
Labels: spike

#123 added alert notifying user of succesfully saving notes to db
  front-end/src/api/index.js
Labels: spike

#124 cleanup unit test
  back-end/app.js
  back-end/functions/getCategories.js
  back-end/functions/postAccessTokenToDatabase.js
  back-end/functions/prettyPrintResponse.js
  back-end/test/test.js
Labels: task

#126 changed faq data to be questions
  back-end/constants/FAQData.js
Labels: task

#128 fixed linking issue on homepage to stats
  front-end/src/pages/Homepage.js
Labels: task

#139 fix console warnings and remove unnecessary files
  back-end/constants/FAQData.js
  front-end/src/components/Accounts/AccountsPage.js
  front-end/src/components/CategoryIcon.js
  front-end/src/components/LoginForm.js
  front-end/src/components/Navbar/Navbar.js
  front-end/src/components/Statistics/Balance/BalanceByAccountList.js
  front-end/src/components/Statistics/Balance/index.js
  front-end/src/components/Statistics/Charts/PieChart.js
  front-end/src/components/TransactionList.js
  front-end/src/pages/Accounts.js
  front-end/src/pages/Homepage.js
  front-end/src/pages/Statistics.js
  front-end/src/pages/TransactionDetail.js
  my-app/.gitignore
  my-app/README.md
  my-app/package-lock.json
  my-app/package.json
  my-app/public/favicon.ico
  my-app/public/index.html
  my-app/public/logo192.png
  my-app/public/logo512.png
  my-app/public/manifest.json
  my-app/public/robots.txt
  my-app/src/App.css
  my-app/src/App.js
  my-app/src/App.test.js
  my-app/src/index.css
  my-app/src/index.js
  my-app/src/logo.svg
  my-app/src/reportWebVitals.js
  my-app/src/setupTests.js
Labels: spike
